name: "VelSupModel_resnet18_general_roll"
gpu: [0,1]
checkpoint:
    filepath: 'logs/'
    monitor: "abs_rel" #abs_rel_pp_gt
    save_top_k: 20
arch:
    max_epochs: 30
model:
    name: 'SelfSupModel' # VelSupModel
    loss: 
        pose_consistency_loss_weight: 0.05
    # checkpoint_path: "logs/models"
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 20
        gamma: 0.5
    depth_net:
        name: 'DepthResNet' # "PydDepth"  PackNetSlim01, PackNet01, DepthResNet
        enc_version: 'resnet18_swsl' #'1A' mobilepydnet
        dec_version: "general" #mobilepydnet
        pretrained: True
    pose_net:
        name: 'PoseResNet' #'PoseNet'
        version: 'resnet18_swsl-pt' # ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
        # max_roll_angle: 20
    train:
        batch_size: 12
        dataset: ['Cityscapes']  #['KITTI', 'Image']
        path: ['/data/datasets/cityscapes_data']  #['/data/datasets/kitti_raw']
        split: ['train'] #'splits/eigen_zhou_files.txt', 
        depth_type: ['']  #'groundtruth'
        repeat: [1]
    validation:
        dataset: ['KITTI']
        path: ['/data/datasets/kitti_raw']
        split: ['splits/eigen_val_files.txt',
                'splits/eigen_test_files.txt']
        depth_type: ['velodyne']
    test:
        dataset: ['KITTI']
        path: ['/data/datasets/kitti_raw']
        split: ['splits/eigen_test_files.txt']
        depth_type: ['velodyne']
