checkpoint:
    filepath: 'logs/'
arch:
    max_epochs: 20
model:
    name: 'VelSupModel'
    # checkpoint_path: "logs/models1"
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet' # PackNetSlim01, PackNet01, DepthResNet
        version: '18pt' #'1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    train:
        batch_size: 20
        dataset: ['KITTI']
        path: ['/data/datasets/kitti-raw']
        split: ['splits/eigen_train_files.txt']
        depth_type: ['velodyne']
        repeat: [2]
    validation:
        batch_size: 12
        dataset: ['KITTI']
        path: ['/data/datasets/kitti-raw']
        split: ['splits/eigen_val_files.txt',
                'splits/eigen_train_files.txt']
        depth_type: ['groundtruth'] # "velodyne", "groundtruth"
    test:
        batch_size: 12
        dataset: ['KITTI']
        path: ['/data/datasets/kitti-raw']
        split: ['splits/eigen_train_files.txt']
        depth_type: ['groundtruth']
